version: '3.6'

networks:
  default:
    name: ${APP_NAME}
    ipam:
      config:
        - subnet: 172.120.120.0/24

services:
  docker-host:
    container_name: ${APP_NAME}_docker-host
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    environment:
      - PORTS=9999
  php:
    container_name: ${APP_NAME}_php
    build: ./php
    volumes:
      - ./../:/var/www

  nginx:
    container_name: ${APP_NAME}_nginx
    build:
      context: ./nginx
    volumes:
      - ./../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - "8080:80"
