name: CI

on: [push]

jobs:
  ci:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        php: [8.1]
    steps:
      - uses: actions/checkout@v1
      - name: Install Composer dependencies
        run: composer install
      - name: Coding standard
        run: php${{ matrix.php }} ./vendor/bin/ecs check src tests public
      - name: PHPUnit
        run: php${{ matrix.php }} ./vendor/bin/phpunit
